### ISSUE TITLE
Folder Name / Project Name

### ISSUE THREAD

**Issue by DraakBZH** [Armoredbrain/videoclub#5]
When I run the script I have an error because it cannot find the containers. The name is not valid.  

This is due to the name of the project folder. The github project is called `videoclub` while the scripts look for `videoclub-backend`. When you clone the repository the folder takes the name of the repository as project name which is therefore not the correct name.

an easy way to fix it, add a file `.env` which contain the variable `COMPOSE_PROJECT_NAME=videoclub-backend`

**Comment by Armoredbrain** [comment]
Ok I changed the project name :D, I will look into dotenv to be able to use environment variable in package.json. But for now the renaming should do the trick.

**Comment by DraakBZH** [comment]
It's work!
