### ISSUE TITLE
setup.sh and docker-compose issue

### ISSUE THREAD

**Issue by DraakBZH** [Armoredbrain/videoclub#6]
When you run setup.sh, you need to add the option `-d` (for detach) to the` docker-compose up` line. Otherwise the script gets stuck at the docker compose. You need a CTRL + C to take control and continue the script but the containers will be shut down and the rest of the script will crash.

**Comment by Armoredbrain** [comment]
Here you go :rocket:

**Comment by DraakBZH** [comment]
It's work!
